base.url=https://jsonplaceholder.typicode.com
oauth.token.url=https://oauth.example.com/token
oauth.client.id=qa-client-id
oauth.client.secret=qa-client-secret
db.url=jdbc:postgresql://qa-db:5432/testdb
db.user=qa_user
db.password=qa_pass
sla.response.ms=2000
env=qa
